In [1]:
!pip install --upgrade numpy==1.22.0
import pandas as pd
import numpy as np

Requirement already satisfied: numpy==1.22.0 in c:\users\mannp\miniconda3\envs\venv\lib\site-packages (1.22.0)

In [2]:
data=pd.read_csv('2022data.csv')

In [3]:
data

,time,tavg,tmin,tmax,prcp,snow,wdir,wspd,wpgt,pres,tsun
0,2022-01-01,9.7,3.8,12.0,0.0,0.0,192.0,8.6,26.6,1027.1,0.0
1,2022-01-02,8.1,3.2,12.0,5.1,0.0,221.0,15.8,62.3,1019.3,96.0
2,2022-01-03,9.8,7.7,12.1,13.6,0.0,230.0,22.3,47.9,1014.3,9.0
3,2022-01-04,7.4,5.8,9.9,19.3,0.0,209.0,16.2,51.5,1000.4,0.0
4,2022-01-05,3.9,1.8,6.1,0.0,0.0,241.0,23.4,54.4,1008.4,126.0
...,...,...,...,...,...,...,...,...,...,...,...
361,2022-12-28,6.9,2.3,10.3,0.0,0.0,202.0,18.7,47.9,1018.1,0.0
362,2022-12-29,10.8,6.3,12.5,4.1,0.0,221.0,29.5,72.4,1010.8,24.0
363,2022-12-30,8.3,4.0,13.4,1.1,0.0,199.0,17.6,48.2,1013.5,127.0
364,2022-12-31,15.5,10.9,17.6,0.0,0.0,221.0,29.9,63.0,1014.7,170.0
365,2023-01-01,12.0,8.1,15.1,0.0,0.0,205.0,11.5,37.1,1019.6,10.0

In [4]:
data=data.drop(['time'],axis=1)

In [5]:
data['wdir'].fillna(value=data['wdir'].mean, inplace=True)

In [6]:
X=data.drop(['tmax'],axis=1)
y=data['tmax']

In [7]:
y
data["wdir"] = pd.to_numeric(data["wdir"], errors='coerce')
data['wdir'] = data['wdir'].astype(float)
data.info()

TypeError: Invalid object type at position 85

In [ ]:
from sklearn.model_selection import train_test_split
X_train , X_test,y_train,y_test=train_test_split(X,y ,test_size=0.2,random_state=42 )
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.fit_transform(X_test)

In [ ]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(X_train,y_train)
predictions=lr.predict(X_test)

In [ ]:
lr.score(X_test,y_test)